# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20140219104801) do

  create_table "final_questionnaires", :force => true do |t|
    t.string   "trainer"
    t.string   "group"
    t.string   "trainee_id_number"
    t.string   "change_of_address"
    t.string   "change_of_adresss_qualitative"
    t.string   "change_of_maritial_status"
    t.string   "change_of_maritial_status_qualitative"
    t.string   "change_of_living_arangements"
    t.string   "change_of_living_arangements_qualitative"
    t.string   "change_of_employment"
    t.string   "employment"
    t.string   "full_time_employment"
    t.string   "part_time_employment"
    t.string   "casual_employment"
    t.string   "other_employment"
    t.string   "other_employment_qualitative"
    t.string   "understandable_training"
    t.string   "helpful_support_visits"
    t.string   "pros_about_training"
    t.string   "improvements_about_training"
    t.string   "what_was_learnt"
    t.string   "what_was_learnt_NB"
    t.string   "most_significant_change"
    t.string   "most_significant_change_qualitative"
    t.string   "still_growing_fq"
    t.string   "why_not_growing"
    t.string   "type_of_veg_garden_trench_bed"
    t.string   "type_of_veg_garden_trench_bed_amount"
    t.string   "type_of_veg_garden_tyre_garden"
    t.string   "type_of_veg_garden_eco_circle"
    t.string   "type_of_veg_garden_container_garden"
    t.string   "type_of_veg_garden_other"
    t.string   "type_of_veg_garden_other_qualitative"
    t.string   "picking_veg"
    t.string   "currently_growing_fq"
    t.string   "still_buying"
    t.string   "money_spent_on_veg_fq"
    t.string   "has_trainee_sold_grown_veg"
    t.string   "profit_from_selling_veg"
    t.string   "has_trainee_swapped_grown_veg"
    t.string   "has_trainee_shared_grown_veg"
    t.string   "has_trainee_given_grown_veg_to_soup_kitchen"
    t.string   "has_trainee_made_jams_and_chutney"
    t.string   "has_trainee_other_grown_veg"
    t.string   "has_trainee_other_grown_veg_qualitative"
    t.string   "health_compaired_to_last_year"
    t.string   "health_problems_diabetes"
    t.string   "health_problems_cancer"
    t.string   "health_problems_arthritis"
    t.string   "health_problems_tb"
    t.string   "health_problems_other"
    t.string   "health_problems_other_qualitative"
    t.string   "feeling_towards_gardening"
    t.string   "spreading_knowelage"
    t.string   "spreading_knowelage_qualitative_pro"
    t.string   "spreading_knowelage_qualitative_neg"
    t.string   "future_gardening_plans"
    t.string   "needs_to_continue_gardening"
    t.string   "knowlage_of_life_skills"
    t.string   "enrollment_plan"
    t.string   "lifeskills_activity_recomendations"
    t.string   "final_words_fq"
    t.string   "trainer_notes_fq"
    t.string   "overall_training_impression"
    t.datetime "created_at",                                  :null => false
    t.datetime "updated_at",                                  :null => false
  end

  create_table "initial_questionnaires", :force => true do |t|
    t.string   "trainer"
    t.string   "group"
    t.string   "area"
    t.string   "basic_details_first_name"
    t.string   "basic_details_last_name"
    t.string   "basic_details_id_number"
    t.string   "basic_details_phone_number"
    t.string   "basic_details_home_address"
    t.string   "basic_details_garden_location"
    t.string   "basic_details_garden_location_qualitative"
    t.string   "basic_details_garden_size_qualitative_l"
    t.string   "basic_details_garden_size_qualitative_w"
    t.string   "basic_details_age"
    t.string   "basic_details_gender"
    t.string   "basic_details_marital_status"
    t.string   "basic_details_living_arrangements"
    t.string   "joining_details_referal"
    t.string   "joining_details_referal_qualitative"
    t.string   "joining_details_joining_reason"
    t.string   "joining_details_potential_growth"
    t.string   "education_levels"
    t.string   "education_levels_other"
    t.string   "employment"
    t.string   "full_time_employment"
    t.string   "part_time_employment"
    t.string   "casual_employment"
    t.string   "other_employment"
    t.string   "other_employment_qualitative"
    t.string   "earning_power"
    t.string   "grant_recieved"
    t.string   "grant_recieved_qualitative"
    t.string   "grant_recieved_amount"
    t.string   "access_to_water"
    t.string   "own_gardening_tools"
    t.string   "gardening_tools_spade"
    t.string   "gardening_tools_shovel"
    t.string   "gardening_tools_rake"
    t.string   "gardening_tools_other"
    t.string   "gardening_tools_other_qualitative"
    t.string   "other_organisations"
    t.string   "which_organisations"
    t.string   "help_recieved"
    t.string   "help_recieved_qualitative"
    t.string   "previous_exerience"
    t.string   "previous_experience_qualitative"
    t.string   "currently_growing"
    t.string   "currently_growing_qualitative_neg"
    t.string   "has_trainee_eaten_grown_veg"
    t.string   "has_trainee_sold_grown_veg"
    t.string   "profit_from_selling_veg"
    t.string   "has_trainee_swapped_grown_veg"
    t.string   "has_trainee_shared_grown_veg"
    t.string   "has_trainee_given_grown_veg_to_soup_kitchen"
    t.string   "has_trainee_made_jams_and_chutney"
    t.string   "has_trainee_other_grown_veg"
    t.string   "has_trainee_other_grown_veg_qualitative"
    #t.string   "is_veg_bought_at_grocery_store_or_market"
   # t.string   "is_veg_bought_at_stand_or_stall"
   # t.string   "is_veg_bought_at_tuck_shop"
  #  t.string   "is_veg_bought_from_friends_or_neighbours"
  #  t.string   "is_veg_bought_from_other"
  #  t.string   "is_veg_bought_from_other_qualitative"
  #  t.string   "money_spent_on_veg"
    t.string   "food_intake"
    t.string   "veg_intake"
    t.string   "general_health"
    t.string   "health_problems_diabetes"
    t.string   "health_problems_cancer"
    t.string   "health_problems_arthritis"
    t.string   "health_problems_tb"
    t.string   "health_problems_other"
    t.string   "health_problems_other_qualitative"
    t.string   "anything_else_to_add"
    t.string   "notes_from_the_trainer"
    t.string   "done"
    t.datetime "created_at",                                  :null => false
    t.datetime "updated_at",                                  :null => false
  end

  create_table "users", :force => true do |t|
    t.string   "email",                  :default => "", :null => false
    t.string   "encrypted_password",     :default => "", :null => false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          :default => 0,  :null => false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.datetime "created_at",                             :null => false
    t.datetime "updated_at",                             :null => false
  end

  add_index "users", ["email"], :name => "index_users_on_email", :unique => true
  add_index "users", ["reset_password_token"], :name => "index_users_on_reset_password_token", :unique => true

  create_table "visits", :force => true do |t|
    t.string   "trainer"
    t.string   "group"
    t.string   "trainee_id_number"
    t.string   "still_growing_sv"
    t.string   "why_trainee_isnt_growing_sv"
    t.string   "mini_nursery"
    t.string   "mini_nursery_rating"
    t.string   "compost_heap"
    t.string   "compost_heap_rating"
    t.string   "trench_bed"
    t.string   "amount_of_trench_beds"
    t.string   "trench_bed_rating"
    t.string   "container_garden"
    t.string   "amount_of_container_gardens"
    t.string   "container_garden_rating"
    t.string   "other_types_of_garden"
    t.string   "other_types_of_garden_kind"
    t.string   "other_types_of_garden_rating"
    t.string   "vegetales_from_garden_sv"
    t.string   "what_eating_from_garden"
    t.string   "trainee_selling_sp"
    t.string   "trainee_selling_sp_qualitative"
    t.string   "trainee_selling_sq_qualitative_amount"
    t.string   "trainee_future_plans"
    t.string   "issues_and_challenges"
    t.string   "garden_postivies"
    t.string   "garden_possibile_improvements"
    t.string   "final_comments_SV"
    t.datetime "created_at",                            :null => false
    t.datetime "updated_at",                            :null => false
  end

end
